### ISSUE TITLE
Transparent TextField outline

### ISSUE THREAD

**Issue by anisalibegic** [kekland/equinox#4] opened 2019-07-06 12:50 UTC
**Describe the bug**
When using **dark theme** the TextField outline is not transparent and it overlays over surrounding widgets.

**To Reproduce**
1. Switch to dark theme
2. Add Column with IconButton and TextField as it's children
3. Focus the TextField
4. See the error

**Expected behavior**
Outline should be transparent in dark theme just like in default theme.

**Screenshots**
![image](https://user-images.githubusercontent.com/12012869/60756380-ebe8fa80-9ffc-11e9-8d09-0e10c0f451b0.png)
![image](https://user-images.githubusercontent.com/12012869/60756401-1b980280-9ffd-11e9-845e-ef470253bb9a.png)

**Comment by kekland** [comment] 2019-07-06 13:13
Whoops, that's a bug in the themes.dart file. `darkTheme` overrides the `outlineColor` variable - which it should not. Will be fixed in the next release, I'll inform you here.

**Comment by kekland** [comment] 2019-07-06 15:29
Accidentally closed. It should be fixed now - can you please check it?

**Comment by anisalibegic** [comment] 2019-07-06 18:23
It's working great on elements above TextField while elements below TextField are overlapping the outline. Is this by the design or a bug to fix?

![image](https://user-images.githubusercontent.com/12012869/60759842-c4f5ed00-a02b-11e9-940d-a4cf875a7469.png)

**Comment by kekland** [comment] 2019-07-06 19:11
I will look into that tomorrow.

**Comment by kekland** [comment] 2019-07-07 12:04
The problem is that in Column, Flutter draws the widgets top-to-bottom. That means that in this case, it will draw the item above TextField, then draw the TextField with its outline, and then then checkbox. But, the outline of the TextField has been drawn before the checkbox, so it will get covered by the checkbox. I don't actually know how to fix this, and that's not covered by the design, so I am not sure what to do. I will try to find a fix later.

**Closed as completed** 2019-07-09 05:32 UTC
